recipe: default.v1
assistant_id: 20230404-131834-round-mint
language: vi
pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
   - name: WhitespaceTokenizer
   - name: RegexFeaturizer
   - name: LexicalSyntacticFeaturizer
   - name: CountVectorsFeaturizer
   - name: CountVectorsFeaturizer
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 4
#     mô hình học sâu DIETClassifier
   - name: DIETClassifier
     epochs: 400
     constrain_similarities: true
   - name: EntitySynonymMapper
   - name: ResponseSelector
     epochs: 400
     constrain_similarities: true
#     ngưỡng đưa ra câu trả lời chính xác và câu dự phòng
   - name: FallbackClassifier
     threshold: 0.9
     ambiguity_threshold: 0.3
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
   - name: MemoizationPolicy
   - name: RulePolicy
   - name: UnexpecTEDIntentPolicy
     max_history: 5
     epochs: 400
   - name: TEDPolicy
     max_history: 5
     epochs: 400
     constrain_similarities: true
